# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18oEUuTuBO5a9Zwt34NKxHmzy6GN6hP3U
"""

import random
import time
from mpi4py import MPI

def monte_carlo_pi(n):
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    size = comm.Get_size()
    
    subset_size = n // size
    subset_start = rank * subset_size
    subset_end = subset_start + subset_size

    count = 0
    for i in range(subset_start, subset_end):
        x = random.random()
        y = random.random()
        if x*x + y*y <= 1:
            count += 1

    pi = comm.reduce(count, op=MPI.SUM, root=0)
    
    if rank == 0:
        pi = (pi / n) * 4
        print("Pi: ", pi)

if __name__ == '__main__':
    start_time = time.time()
    monte_carlo_pi(10000000)
    end_time = time.time()
    print("Time taken: ", end_time - start_time)